exports.config = {
    packid: 'default',
    background: {
        classic: {
            pack_id: 'default',
            category: 'background',
            id: 'classic',
            src: '../static/bg/classic.png',
            name: '经典',
        },
        desert: {
            pack_id: 'default',
            category: 'background',
            id: 'desert',
            src: '../static/bg/desert.png',
            name: '室内',
        },
        night: {
            pack_id: 'default',
            category: 'background',
            id: 'night',
            src: '../static/bg/night.png',
            name: '夜色',
        },
        casino: {
            pack_id: 'default',
            category: 'background',
            id: 'casino',
            src: '../static/bg/casino.png',
            name: '俱乐部',
        },
        'mid-autumn': {
            pack_id: 'default',
            category: 'background',
            id: 'mid-autumn',
            src: '../static/bg/mid-autumn.png',
            name: '中秋',
        },
        halloween: {
            pack_id: 'default',
            category: 'background',
            id: 'halloween',
            src: '../static/bg/halloween.png',
            name: '万圣节',
        },
    },
    mouth: {
        mouth26: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth26',
            order: 26,
            src: '../static/clothes/mouth/26.png',
            style: {
                left: '-0.225rem',
                top: '-0.285rem',
                zIndex: 230,
                width: '0.175rem',
                height: '0.09rem',
            },
            tag: 'new',
        },
        mouth27: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth27',
            order: 27,
            src: '../static/clothes/mouth/27.png',
            style: {
                left: '-0.24rem',
                top: '-0.275rem',
                zIndex: 230,
                width: '0.205rem',
                height: '0.05rem',
            },
            tag: 'new',
        },
        mouth00: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth00',
            order: 0,
            src: '../static/clothes/mouth/00.png',
            style: {
                left: '-0.195rem',
                top: '-0.295rem',
                zIndex: 230,
                width: '0.11rem',
                height: '0.035rem',
            },
        },
        mouth01: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth01',
            order: 1,
            src: '../static/clothes/mouth/01.png',
            style: {
                left: '-0.21rem',
                top: '-0.285rem',
                zIndex: 230,
                width: '0.14rem',
                height: '0.06rem',
            },
        },
        mouth02: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth02',
            order: 2,
            src: '../static/clothes/mouth/02.png',
            style: {
                left: '-0.205rem',
                top: '-0.285rem',
                zIndex: 230,
                width: '0.135rem',
                height: '0.06rem',
            },
        },
        mouth03: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth03',
            order: 3,
            src: '../static/clothes/mouth/03.png',
            style: {
                left: '-0.18rem',
                top: '-0.305rem',
                zIndex: 230,
                width: '0.095rem',
                height: '0.11rem',
            },
        },
        mouth04: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth04',
            order: 4,
            src: '../static/clothes/mouth/04.png',
            style: {
                left: '-0.175rem',
                top: '-0.29rem',
                zIndex: 230,
                width: '0.07rem',
                height: '0.095rem',
            },
        },
        mouth05: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth05',
            order: 5,
            src: '../static/clothes/mouth/05.png',
            style: {
                left: '-0.235rem',
                top: '-0.29rem',
                zIndex: 230,
                width: '0.2rem',
                height: '0.11rem',
            },
        },
        mouth06: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth06',
            order: 6,
            src: '../static/clothes/mouth/06.png',
            style: {
                left: '-0.25rem',
                top: '-0.285rem',
                zIndex: 230,
                width: '0.23rem',
                height: '0.125rem',
            },
        },
        mouth07: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth07',
            order: 7,
            src: '../static/clothes/mouth/07.png',
            style: {
                left: '-0.235rem',
                top: '-0.285rem',
                zIndex: 230,
                width: '0.205rem',
                height: '0.18rem',
            },
        },
        mouth08: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth08',
            order: 8,
            src: '../static/clothes/mouth/08.png',
            style: {
                left: '-0.205rem',
                top: '-0.29rem',
                zIndex: 230,
                width: '0.12rem',
                height: '0.07rem',
            },
        },
        mouth09: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth09',
            order: 9,
            src: '../static/clothes/mouth/09.png',
            style: {
                left: '-0.24rem',
                top: '-0.29rem',
                zIndex: 230,
                width: '0.205rem',
                height: '0.09rem',
            },
        },
        mouth10: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth10',
            order: 10,
            src: '../static/clothes/mouth/10.png',
            style: {
                left: '-0.245rem',
                top: '-0.28rem',
                zIndex: 230,
                width: '0.21rem',
                height: '0.08rem',
            },
        },
        mouth11: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth11',
            order: 11,
            src: '../static/clothes/mouth/11.png',
            style: {
                left: '-0.255rem',
                top: '-0.275rem',
                zIndex: 230,
                width: '0.25rem',
                height: '0.085rem',
            },
        },
        mouth12: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth12',
            order: 12,
            src: '../static/clothes/mouth/12.png',
            style: {
                left: '-0.31rem',
                top: '-0.295rem',
                zIndex: 230,
                width: '0.38rem',
                height: '0.125rem',
            },
        },
        mouth13: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth13',
            order: 13,
            src: '../static/clothes/mouth/13.png',
            style: {
                left: '-0.22rem',
                top: '-0.275rem',
                zIndex: 230,
                width: '0.15rem',
                height: '0.055rem',
            },
        },
        mouth14: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth14',
            order: 14,
            src: '../static/clothes/mouth/14.png',
            style: {
                left: '-0.305rem',
                top: '-0.29rem',
                zIndex: 230,
                width: '0.4rem',
                height: '0.06rem',
            },
        },
        mouth15: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth15',
            order: 15,
            src: '../static/clothes/mouth/15.png',
            style: {
                left: '-0.295rem',
                top: '-0.3rem',
                zIndex: 230,
                width: '0.35rem',
                height: '0.11rem',
            },
        },
        mouth16: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth16',
            order: 16,
            src: '../static/clothes/mouth/16.png',
            style: {
                left: '-0.26rem',
                top: '-0.295rem',
                zIndex: 230,
                width: '0.25rem',
                height: '0.1rem',
            },
        },
        mouth17: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth17',
            order: 17,
            src: '../static/clothes/mouth/17.png',
            style: {
                left: '-0.32rem',
                top: '-0.285rem',
                zIndex: 230,
                width: '0.42rem',
                height: '0.13rem',
            },
        },
        mouth18: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth18',
            order: 18,
            src: '../static/clothes/mouth/18.png',
            style: {
                left: '-0.29rem',
                top: '-0.29rem',
                zIndex: 230,
                width: '0.315rem',
                height: '0.22rem',
            },
        },
        mouth19: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth19',
            order: 19,
            src: '../static/clothes/mouth/19.png',
            style: {
                left: '-0.285rem',
                top: '-0.285rem',
                zIndex: 230,
                width: '0.32rem',
                height: '0.14rem',
            },
        },
        mouth20: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth20',
            order: 20,
            src: '../static/clothes/mouth/20.png',
            style: {
                left: '-0.375rem',
                top: '-0.32rem',
                zIndex: 230,
                width: '0.745rem',
                height: '0.27rem',
            },
        },
        mouth21: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth21',
            order: 21,
            src: '../static/clothes/mouth/21.png',
            style: {
                left: '-0.305rem',
                top: '-0.29rem',
                zIndex: 230,
                width: '0.355rem',
                height: '0.19rem',
            },
        },
        mouth24: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth24',
            order: 24,
            src: '../static/clothes/mouth/24.png',
            style: {
                left: '-0.395rem',
                top: '-0.3rem',
                zIndex: 230,
                width: '0.29rem',
                height: '0.165rem',
            },
        },
        mouth25: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth25',
            order: 25,
            src: '../static/clothes/mouth/25.png',
            style: {
                left: '-0.225rem',
                top: '-0.29rem',
                zIndex: 230,
                width: '0.165rem',
                height: '0.135rem',
            },
        },
        mouth22: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth22',
            order: 22,
            src: '../static/clothes/mouth/22.png',
            style: {
                left: '-0.25rem',
                top: '-0.31rem',
                zIndex: 230,
                width: '0.205rem',
                height: '0.245rem',
            },
            tag: 'lock2',
        },
        mouth23: {
            pack_id: 'default',
            category: 'mouth',
            id: 'mouth23',
            order: 23,
            src: '../static/clothes/mouth/23.png',
            style: {
                left: '-0.43rem',
                top: '-0.26rem',
                zIndex: 230,
                width: '0.29rem',
                height: '0.175rem',
            },
            tag: 'lock7',
        },
    },
    headwear: {
        headwear31: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear31',
            order: 31,
            src: '../static/clothes/headwear/31.png',
            style: {
                left: '-0.42rem',
                top: '-0.775rem',
                zIndex: 240,
                width: '0.88rem',
                height: '0.83rem',
            },
            tag: 'new',
        },
        headwear32: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear32',
            order: 32,
            src: '../static/clothes/headwear/32.png',
            style: {
                left: '-0.42rem',
                top: '-0.855rem',
                zIndex: 240,
                width: '0.875rem',
                height: '0.955rem',
            },
            tag: 'new',
        },
        headwear33: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear33',
            order: 33,
            src: '../static/clothes/headwear/33.png',
            style: {
                left: '-0.4rem',
                top: '-0.845rem',
                zIndex: 240,
                width: '0.81rem',
                height: '0.72rem',
            },
            tag: 'new',
        },
        headwear34: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear34',
            order: 34,
            src: '../static/clothes/headwear/34.png',
            style: {
                left: '-0.44rem',
                top: '-0.825rem',
                zIndex: 240,
                width: '0.85rem',
                height: '0.635rem',
            },
            tag: 'new',
        },
        headwear01: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear01',
            order: 1,
            src: '../static/clothes/headwear/01.png',
            style: {
                left: '-0.355rem',
                top: '-0.7rem',
                zIndex: 240,
                width: '0.66rem',
                height: '0.26rem',
            },
        },
        headwear02: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear02',
            order: 2,
            src: '../static/clothes/headwear/02.png',
            style: {
                left: '-0.305rem',
                top: '-0.7rem',
                zIndex: 240,
                width: '0.39rem',
                height: '0.175rem',
            },
        },
        headwear03: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear03',
            order: 3,
            src: '../static/clothes/headwear/03.png',
            style: {
                left: '-0.215rem',
                top: '-0.84rem',
                zIndex: 240,
                width: '0.285rem',
                height: '0.275rem',
            },
        },
        headwear04: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear04',
            order: 4,
            src: '../static/clothes/headwear/04.png',
            style: {
                left: '-0.355rem',
                top: '-0.71rem',
                zIndex: 240,
                width: '0.665rem',
                height: '0.27rem',
            },
        },
        headwear05: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear05',
            order: 5,
            src: '../static/clothes/headwear/05.png',
            style: {
                left: '-0.39rem',
                top: '-0.825rem',
                zIndex: 240,
                width: '0.75rem',
                height: '0.48rem',
            },
        },
        headwear06: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear06',
            order: 6,
            src: '../static/clothes/headwear/06.png',
            style: {
                left: '-0.47rem',
                top: '-0.785rem',
                zIndex: 240,
                width: '0.885rem',
                height: '0.585rem',
            },
        },
        headwear07: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear07',
            order: 7,
            src: '../static/clothes/headwear/07.png',
            style: {
                left: '-0.46rem',
                top: '-0.96rem',
                zIndex: 240,
                width: '0.945rem',
                height: '0.735rem',
            },
        },
        headwear08: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear08',
            order: 8,
            src: '../static/clothes/headwear/08.png',
            style: {
                left: '-0.435rem',
                top: '-0.845rem',
                zIndex: 240,
                width: '0.875rem',
                height: '0.625rem',
            },
        },
        headwear09: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear09',
            order: 9,
            src: '../static/clothes/headwear/09.png',
            style: {
                left: '-0.32rem',
                top: '-0.73rem',
                zIndex: 240,
                width: '0.78rem',
                height: '0.72rem',
            },
        },
        headwear10: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear10',
            order: 10,
            src: '../static/clothes/headwear/10.png',
            style: {
                left: '-0.36rem',
                top: '-0.61rem',
                zIndex: 240,
                width: '0.685rem',
                height: '0.205rem',
            },
        },
        headwear11: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear11',
            order: 11,
            src: '../static/clothes/headwear/11.png',
            style: {
                left: '-0.395rem',
                top: '-0.815rem',
                zIndex: 240,
                width: '0.99rem',
                height: '0.81rem',
            },
        },
        headwear12: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear12',
            order: 12,
            src: '../static/clothes/headwear/12.png',
            style: {
                left: '-0.38rem',
                top: '-0.835rem',
                zIndex: 240,
                width: '1.045rem',
                height: '0.785rem',
            },
        },
        headwear13: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear13',
            order: 13,
            src: '../static/clothes/headwear/13.png',
            style: {
                left: '-0.375rem',
                top: '-0.86rem',
                zIndex: 240,
                width: '0.71rem',
                height: '0.52rem',
            },
        },
        headwear14: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear14',
            order: 14,
            src: '../static/clothes/headwear/14.png',
            style: {
                left: '-0.405rem',
                top: '-0.785rem',
                zIndex: 240,
                width: '0.89rem',
                height: '0.725rem',
            },
        },
        headwear15: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear15',
            order: 15,
            src: '../static/clothes/headwear/15.png',
            style: {
                left: '-0.36rem',
                top: '-0.79rem',
                zIndex: 240,
                width: '0.715rem',
                height: '0.5rem',
            },
        },
        headwear16: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear16',
            order: 16,
            src: '../static/clothes/headwear/16.png',
            style: {
                left: '-0.475rem',
                top: '-0.8rem',
                zIndex: 240,
                width: '1.025rem',
                height: '0.615rem',
            },
        },
        headwear17: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear17',
            order: 17,
            src: '../static/clothes/headwear/17.png',
            style: {
                left: '-0.44rem',
                top: '-0.775rem',
                zIndex: 240,
                width: '0.915rem',
                height: '0.635rem',
            },
        },
        headwear18: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear18',
            order: 18,
            src: '../static/clothes/headwear/18.png',
            style: {
                left: '-0.49rem',
                top: '-0.855rem',
                zIndex: 240,
                width: '1.005rem',
                height: '0.665rem',
            },
        },
        headwear19: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear19',
            order: 19,
            src: '../static/clothes/headwear/19.png',
            style: {
                left: '-0.455rem',
                top: '-0.825rem',
                zIndex: 240,
                width: '1.01rem',
                height: '0.75rem',
            },
        },
        headwear20: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear20',
            order: 20,
            src: '../static/clothes/headwear/20.png',
            style: {
                left: '-0.365rem',
                top: '-0.74rem',
                zIndex: 240,
                width: '0.805rem',
                height: '0.415rem',
            },
        },
        headwear21: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear21',
            order: 21,
            src: '../static/clothes/headwear/21.png',
            style: {
                left: '-0.395rem',
                top: '-0.795rem',
                zIndex: 240,
                width: '0.68rem',
                height: '0.3rem',
            },
        },
        headwear22: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear22',
            order: 22,
            src: '../static/clothes/headwear/22.png',
            style: {
                left: '-0.51rem',
                top: '-0.9rem',
                zIndex: 240,
                width: '1.015rem',
                height: '0.755rem',
            },
        },
        headwear25: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear25',
            order: 25,
            src: '../static/clothes/headwear/25.png',
            style: {
                left: '-0.365rem',
                top: '-0.93rem',
                zIndex: 240,
                width: '0.9rem',
                height: '0.725rem',
            },
        },
        headwear26: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear26',
            order: 26,
            src: '../static/clothes/headwear/26.png',
            style: {
                left: '-0.37rem',
                top: '-0.9rem',
                zIndex: 240,
                width: '0.75rem',
                height: '0.64rem',
            },
        },
        headwear27: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear27',
            order: 27,
            src: '../static/clothes/headwear/27.png',
            style: {
                left: '-0.365rem',
                top: '-0.745rem',
                zIndex: 240,
                width: '0.905rem',
                height: '0.77rem',
            },
        },
        headwear28: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear28',
            order: 28,
            src: '../static/clothes/headwear/28.png',
            style: {
                left: '-0.395rem',
                top: '-0.86rem',
                zIndex: 240,
                width: '0.755rem',
                height: '0.54rem',
            },
        },
        headwear29: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear29',
            order: 29,
            src: '../static/clothes/headwear/29.png',
            style: {
                left: '-0.395rem',
                top: '-0.72rem',
                zIndex: 240,
                width: '0.79rem',
                height: '0.765rem',
            },
        },
        headwear30: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear30',
            order: 30,
            src: '../static/clothes/headwear/30.png',
            style: {
                left: '-0.42rem',
                top: '-0.835rem',
                zIndex: 240,
                width: '0.8rem',
                height: '0.5rem',
            },
        },
        headwear23: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear23',
            order: 23,
            src: '../static/clothes/headwear/23.png',
            style: {
                left: '-0.445rem',
                top: '-0.845rem',
                zIndex: 240,
                width: '0.85rem',
                height: '0.615rem',
            },
            tag: 'lock2',
        },
        headwear24: {
            pack_id: 'default',
            category: 'headwear',
            id: 'headwear24',
            order: 24,
            src: '../static/clothes/headwear/24.png',
            style: {
                left: '-0.395rem',
                top: '-0.73rem',
                zIndex: 240,
                width: '0.77rem',
                height: '0.735rem',
            },
            tag: 'lock7',
        },
    },
    glass: {
        glass20: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass20',
            order: 20,
            src: '../static/clothes/glass/20.png',
            style: {
                left: '-0.325rem',
                top: '-0.735rem',
                zIndex: 250,
                width: '0.63rem',
                height: '0.3rem',
            },
            tag: 'new',
        },
        glass21: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass21',
            order: 21,
            src: '../static/clothes/glass/21.png',
            style: {
                left: '-0.41rem',
                top: '-0.51rem',
                zIndex: 250,
                width: '0.615rem',
                height: '0.26rem',
            },
            tag: 'new',
        },
        glass22: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass22',
            order: 22,
            src: '../static/clothes/glass/22.png',
            style: {
                left: '0.065rem',
                top: '-0.75rem',
                zIndex: 250,
                width: '0.295rem',
                height: '0.28rem',
            },
            tag: 'new',
        },
        glass01: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass01',
            order: 1,
            src: '../static/clothes/glass/01.png',
            style: {
                left: '-0.395rem',
                top: '-0.525rem',
                zIndex: 250,
                width: '0.53rem',
                height: '0.28rem',
            },
        },
        glass02: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass02',
            order: 2,
            src: '../static/clothes/glass/02.png',
            style: {
                left: '-0.405rem',
                top: '-0.475rem',
                zIndex: 250,
                width: '0.595rem',
                height: '0.2rem',
            },
        },
        glass03: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass03',
            order: 3,
            src: '../static/clothes/glass/03.png',
            style: {
                left: '-0.405rem',
                top: '-0.495rem',
                zIndex: 250,
                width: '0.57rem',
                height: '0.235rem',
            },
        },
        glass04: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass04',
            order: 4,
            src: '../static/clothes/glass/04.png',
            style: {
                left: '-0.39rem',
                top: '-0.485rem',
                zIndex: 250,
                width: '0.535rem',
                height: '0.24rem',
            },
        },
        glass05: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass05',
            order: 5,
            src: '../static/clothes/glass/05.png',
            style: {
                left: '-0.14rem',
                top: '-0.515rem',
                zIndex: 250,
                width: '0.325rem',
                height: '0.4rem',
            },
        },
        glass06: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass06',
            order: 6,
            src: '../static/clothes/glass/06.png',
            style: {
                left: '-0.32rem',
                top: '-0.56rem',
                zIndex: 250,
                width: '0.635rem',
                height: '0.3rem',
            },
        },
        glass07: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass07',
            order: 7,
            src: '../static/clothes/glass/07.png',
            style: {
                left: '-0.385rem',
                top: '-0.475rem',
                zIndex: 250,
                width: '0.52rem',
                height: '0.215rem',
            },
        },
        glass08: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass08',
            order: 8,
            src: '../static/clothes/glass/08.png',
            style: {
                left: '-0.39rem',
                top: '-0.5rem',
                zIndex: 250,
                width: '0.55rem',
                height: '0.22rem',
            },
        },
        glass09: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass09',
            order: 9,
            src: '../static/clothes/glass/09.png',
            style: {
                left: '-0.14rem',
                top: '-0.605rem',
                zIndex: 250,
                width: '0.545rem',
                height: '0.345rem',
            },
        },
        glass10: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass10',
            order: 10,
            src: '../static/clothes/glass/10.png',
            style: {
                left: '0.15rem',
                top: '-0.54rem',
                zIndex: 250,
                width: '0.265rem',
                height: '0.265rem',
            },
        },
        glass11: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass11',
            order: 11,
            src: '../static/clothes/glass/11.png',
            style: {
                left: '0.15rem',
                top: '-0.54rem',
                zIndex: 250,
                width: '0.265rem',
                height: '0.25rem',
            },
        },
        glass12: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass12',
            order: 12,
            src: '../static/clothes/glass/12.png',
            style: {
                left: '-0.085rem',
                top: '-0.89rem',
                zIndex: 250,
                width: '0.445rem',
                height: '0.345rem',
            },
        },
        glass13: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass13',
            order: 13,
            src: '../static/clothes/glass/13.png',
            style: {
                left: '-0.325rem',
                top: '-0.75rem',
                zIndex: 250,
                width: '0.55rem',
                height: '0.21rem',
            },
        },
        glass14: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass14',
            order: 14,
            src: '../static/clothes/glass/14.png',
            style: {
                left: '-0.37rem',
                top: '-0.875rem',
                zIndex: 250,
                width: '0.66rem',
                height: '0.31rem',
            },
        },
        glass17: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass17',
            order: 17,
            src: '../static/clothes/glass/17.png',
            style: {
                left: '-0.385rem',
                top: '-0.555rem',
                zIndex: 250,
                width: '0.925rem',
                height: '0.28rem',
            },
        },
        glass18: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass18',
            order: 18,
            src: '../static/clothes/glass/18.png',
            style: {
                left: '-0.05rem',
                top: '-0.995rem',
                zIndex: 250,
                width: '0.44rem',
                height: '0.495rem',
            },
        },
        glass19: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass19',
            order: 19,
            src: '../static/clothes/glass/19.png',
            style: {
                left: '-0.31rem',
                top: '-0.775rem',
                zIndex: 250,
                width: '0.52rem',
                height: '0.24rem',
            },
        },
        glass15: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass15',
            order: 15,
            src: '../static/clothes/glass/15.png',
            style: {
                left: '0.08rem',
                top: '-0.875rem',
                zIndex: 250,
                width: '0.245rem',
                height: '0.29rem',
            },
            tag: 'lock2',
        },
        glass16: {
            pack_id: 'default',
            category: 'glass',
            id: 'glass16',
            order: 16,
            src: '../static/clothes/glass/16.png',
            style: {
                left: '-0.295rem',
                top: '-0.895rem',
                zIndex: 250,
                width: '0.52rem',
                height: '0.23rem',
            },
            tag: 'lock7',
        },
    },
    body: {
        body22: {
            pack_id: 'default',
            category: 'body',
            id: 'body22',
            order: 22,
            src: '../static/clothes/body/22.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
            tag: 'new',
        },
        body23: {
            pack_id: 'default',
            category: 'body',
            id: 'body23',
            order: 23,
            src: '../static/clothes/body/23.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
            tag: 'new',
        },
        body00: {
            pack_id: 'default',
            category: 'body',
            id: 'body00',
            order: 0,
            src: '../static/clothes/body/00.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body01: {
            pack_id: 'default',
            category: 'body',
            id: 'body01',
            order: 1,
            src: '../static/clothes/body/01.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body02: {
            pack_id: 'default',
            category: 'body',
            id: 'body02',
            order: 2,
            src: '../static/clothes/body/02.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body03: {
            pack_id: 'default',
            category: 'body',
            id: 'body03',
            order: 3,
            src: '../static/clothes/body/03.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body04: {
            pack_id: 'default',
            category: 'body',
            id: 'body04',
            order: 4,
            src: '../static/clothes/body/04.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body05: {
            pack_id: 'default',
            category: 'body',
            id: 'body05',
            order: 5,
            src: '../static/clothes/body/05.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body06: {
            pack_id: 'default',
            category: 'body',
            id: 'body06',
            order: 6,
            src: '../static/clothes/body/06.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body07: {
            pack_id: 'default',
            category: 'body',
            id: 'body07',
            order: 7,
            src: '../static/clothes/body/07.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body08: {
            pack_id: 'default',
            category: 'body',
            id: 'body08',
            order: 8,
            src: '../static/clothes/body/08.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body09: {
            pack_id: 'default',
            category: 'body',
            id: 'body09',
            order: 9,
            src: '../static/clothes/body/09.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body10: {
            pack_id: 'default',
            category: 'body',
            id: 'body10',
            order: 10,
            src: '../static/clothes/body/10.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body11: {
            pack_id: 'default',
            category: 'body',
            id: 'body11',
            order: 11,
            src: '../static/clothes/body/11.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body12: {
            pack_id: 'default',
            category: 'body',
            id: 'body12',
            order: 12,
            src: '../static/clothes/body/12.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body13: {
            pack_id: 'default',
            category: 'body',
            id: 'body13',
            order: 13,
            src: '../static/clothes/body/13.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body14: {
            pack_id: 'default',
            category: 'body',
            id: 'body14',
            order: 14,
            src: '../static/clothes/body/14.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body15: {
            pack_id: 'default',
            category: 'body',
            id: 'body15',
            order: 15,
            src: '../static/clothes/body/15.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body16: {
            pack_id: 'default',
            category: 'body',
            id: 'body16',
            order: 16,
            src: '../static/clothes/body/16.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body17: {
            pack_id: 'default',
            category: 'body',
            id: 'body17',
            order: 17,
            src: '../static/clothes/body/17.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body18: {
            pack_id: 'default',
            category: 'body',
            id: 'body18',
            order: 18,
            src: '../static/clothes/body/18.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body19: {
            pack_id: 'default',
            category: 'body',
            id: 'body19',
            order: 19,
            src: '../static/clothes/body/19.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body20: {
            pack_id: 'default',
            category: 'body',
            id: 'body20',
            order: 20,
            src: '../static/clothes/body/20.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
        body21: {
            pack_id: 'default',
            category: 'body',
            id: 'body21',
            order: 21,
            src: '../static/clothes/body/21.png',
            style: {
                left: '-0.375rem',
                top: '-0.7rem',
                zIndex: 210,
                width: '0.75rem',
                height: '0.7rem',
            },
        },
    },
    eye: {
        eye18: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye18',
            order: 18,
            src: '../static/clothes/eye/18.png',
            style: {
                left: '-0.32rem',
                top: '-0.475rem',
                zIndex: 220,
                width: '0.4rem',
                height: '0.19rem',
            },
            tag: 'new',
        },
        eye19: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye19',
            order: 19,
            src: '../static/clothes/eye/19.png',
            style: {
                left: '-0.33rem',
                top: '-0.48rem',
                zIndex: 220,
                width: '0.42rem',
                height: '0.21rem',
            },
            tag: 'new',
        },
        eye00: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye00',
            order: 0,
            src: '../static/clothes/eye/00.png',
            style: {
                left: '-0.28rem',
                top: '-0.405rem',
                zIndex: 220,
                width: '0.295rem',
                height: '0.075rem',
            },
        },
        eye01: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye01',
            order: 1,
            src: '../static/clothes/eye/01.png',
            style: {
                left: '-0.3rem',
                top: '-0.4rem',
                zIndex: 220,
                width: '0.34rem',
                height: '0.075rem',
            },
        },
        eye02: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye02',
            order: 2,
            src: '../static/clothes/eye/02.png',
            style: {
                left: '-0.29rem',
                top: '-0.39rem',
                zIndex: 220,
                width: '0.33rem',
                height: '0.065rem',
            },
        },
        eye03: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye03',
            order: 3,
            src: '../static/clothes/eye/03.png',
            style: {
                left: '-0.28rem',
                top: '-0.39rem',
                zIndex: 220,
                width: '0.29rem',
                height: '0.06rem',
            },
        },
        eye04: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye04',
            order: 4,
            src: '../static/clothes/eye/04.png',
            style: {
                left: '-0.305rem',
                top: '-0.385rem',
                zIndex: 220,
                width: '0.345rem',
                height: '0.065rem',
            },
        },
        eye05: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye05',
            order: 5,
            src: '../static/clothes/eye/05.png',
            style: {
                left: '-0.31rem',
                top: '-0.425rem',
                zIndex: 220,
                width: '0.415rem',
                height: '0.105rem',
            },
        },
        eye06: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye06',
            order: 6,
            src: '../static/clothes/eye/06.png',
            style: {
                left: '-0.32rem',
                top: '-0.47rem',
                zIndex: 220,
                width: '0.4rem',
                height: '0.18rem',
            },
        },
        eye07: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye07',
            order: 7,
            src: '../static/clothes/eye/07.png',
            style: {
                left: '-0.32rem',
                top: '-0.465rem',
                zIndex: 220,
                width: '0.4rem',
                height: '0.17rem',
            },
        },
        eye08: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye08',
            order: 8,
            src: '../static/clothes/eye/08.png',
            style: {
                left: '-0.3rem',
                top: '-0.415rem',
                zIndex: 220,
                width: '0.36rem',
                height: '0.095rem',
            },
        },
        eye09: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye09',
            order: 9,
            src: '../static/clothes/eye/09.png',
            style: {
                left: '-0.325rem',
                top: '-0.445rem',
                zIndex: 220,
                width: '0.42rem',
                height: '0.17rem',
            },
        },
        eye10: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye10',
            order: 10,
            src: '../static/clothes/eye/10.png',
            style: {
                left: '-0.32rem',
                top: '-0.48rem',
                zIndex: 220,
                width: '0.415rem',
                height: '0.195rem',
            },
        },
        eye11: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye11',
            order: 11,
            src: '../static/clothes/eye/11.png',
            style: {
                left: '-0.315rem',
                top: '-0.46rem',
                zIndex: 220,
                width: '0.39rem',
                height: '0.155rem',
            },
        },
        eye12: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye12',
            order: 12,
            src: '../static/clothes/eye/12.png',
            style: {
                left: '-0.31rem',
                top: '-0.445rem',
                zIndex: 220,
                width: '0.38rem',
                height: '0.155rem',
            },
        },
        eye13: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye13',
            order: 13,
            src: '../static/clothes/eye/13.png',
            style: {
                left: '-0.3rem',
                top: '-0.42rem',
                zIndex: 220,
                width: '0.355rem',
                height: '0.095rem',
            },
        },
        eye14: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye14',
            order: 14,
            src: '../static/clothes/eye/14.png',
            style: {
                left: '-0.305rem',
                top: '-0.42rem',
                zIndex: 220,
                width: '0.37rem',
                height: '0.115rem',
            },
        },
        eye15: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye15',
            order: 15,
            src: '../static/clothes/eye/15.png',
            style: {
                left: '-0.285rem',
                top: '-0.39rem',
                zIndex: 220,
                width: '0.34rem',
                height: '0.1rem',
            },
        },
        eye16: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye16',
            order: 16,
            src: '../static/clothes/eye/16.png',
            style: {
                left: '-0.33rem',
                top: '-0.43rem',
                zIndex: 220,
                width: '0.43rem',
                height: '0.105rem',
            },
        },
        eye17: {
            pack_id: 'default',
            category: 'eye',
            id: 'eye17',
            order: 17,
            src: '../static/clothes/eye/17.png',
            style: {
                left: '-0.32rem',
                top: '-0.395rem',
                zIndex: 220,
                width: '0.405rem',
                height: '0.1rem',
            },
        },
    },
}
